{% set version = "1.2.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gdalutilities
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gdalUtilities_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gdalUtilities/gdalUtilities_{{ version }}.tar.gz
  sha256: 2a72e990080ad626205c78edc6614959b564413b7fc23132008b7259723571a7

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-sf >=1.0_11
  run:
    - r-base
    - r-sf >=1.0_11

test:
  commands:
    - $R -e "library('gdalUtilities')"           # [not win]
    - "\"%R%\" -e \"library('gdalUtilities')\""  # [win]

about:
  home: https://github.com/JoshOBrien/gdalUtilities/
  license: GPL-2.0-or-later
  summary: R's 'sf' package ships with self-contained 'GDAL' executables, including a bare bones interface to several 'GDAL'-related utility programs collectively known as the 'GDAL utilities'. For each of those utilities, this package provides an R wrapper whose formal arguments closely mirror those of the 'GDAL' command
    line interface. The utilities operate on data stored in files and typically write their output to other files. Therefore, to process data stored in any of R's more common spatial formats (i.e. those supported by the 'sp', 'sf', and 'raster' packages), first write them to disk, then process them with the package's wrapper
    functions before reading the outputted results back into R. GDAL function arguments introduced in GDAL version 3.2.1 or earlier are supported.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - TomAugspurger
